### ISSUE TITLE
Stream pauses when ads are blocked

### ISSUE THREAD

**Issue by david-jones-git** [emiraleph/TwitchAdUBlockOrigin#1]
If this is still being maintained: I noticed that the stream frequently gets stuck in a loading screen after ads are blocked. To resume the stream, the pause/play button must be clicked twice.

**Comment by emiraleph** [comment]
Thank you very much for letting me know, since I manage the project and others in my free time, I have not been able to dedicate enough time to it, I will try to solve the error you mention, thanks for informing me
